const mongoose=require("mongoose")
const jobSchema=new mongoose.Schema({
    companyName:{
        type:String,
        require:true
    },
    logo:{
        type:String,
        require:true
    },
    position:{
        type:String,
        require:true
    },
    monthlySalary:{
        type:String,
        require:true
    }, 
    jobType:{
        type:String,
        require:true
    },
    mode:{
        type:String,
        require:true
    },
    location:{
        type:String,
        require:true
    },
    description:{
        type:String,
        require:true
    },
    aboutCompany:{
        type:String,
        require:true
    },
    skillRequired:{
        type:String,
        require:true
    },
    information:{
        type:String,
        require:true
    }
})
const Job=mongoose.model('Job',jobSchema);
module.exports={Job}